### ISSUE TITLE
Styled function Autocomplete don't work

### ISSUE THREAD

**Issue by matifriaz** [nandorojo/dripsy#279]
After updating Dripsy and Typescript. Typescript is showing us this error

`Type '{ width: number; height: number; }' is not assignable to type 'FactoryValue<ResponsiveValue<string | number | (string & {})>>'.
  Object literal may only specify known properties, and 'width' does not exist in type '(string | number | (string & {}))[] | readonly (string | number | (string & {}))[] | ((theme: DripsyFinalTheme) => ResponsiveValue<string | number | (string & {})>)'.ts(2322)`
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/76031462/229703663-792e51f4-58b0-4f31-9b9b-d633ad68704c.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/76031462/229703556-d8d95485-bc02-4d9a-9d35-23240c9a66b1.png">

**Comment by matifriaz** [comment]
And also the autocomplete in styled function is not working 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/76031462/229706066-78a86231-61dc-4fab-a8b0-464cf5ed64d0.png">


I believe the issue is with the StyledProps. 
<img width="865" alt="image" src="https://user-images.githubusercontent.com/76031462/229706952-65fc56fe-1982-48f5-8f7a-fa72bf65c6c4.png">

**Comment by nandorojo** [comment]
thanks for reporting this, i’ll look into the inline shadows. i only tested the `boxShadow` variant property

**Comment by nandorojo** [comment]
Fixed in `4.0.2`

**Comment by matifriaz** [comment]
The issue is still there. The Typescript intellisense not showing me any style. 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/76031462/230372115-1517ccc6-0141-4737-bca2-7fd46996f9bd.png">

**Comment by mo-fouad** [comment]
I am having the same issue with the View component on Version 4.0.2
my usage is like this, 
`<View
        sx={{ 
          shadowOffset: { width: 0, height: 4 }, 
        }}
      >`
     
![Screenshot 2023-04-08 at 05 02 03](https://user-images.githubusercontent.com/24290379/230700496-0a4149c4-8bdf-4e52-8992-792700a75e61.png)

**Comment by mo-fouad** [comment]
@matifriaz I have updated to TypsScript 5, and Every thing working as Magic :D

**Comment by nandorojo** [comment]
great!

**Comment by nandorojo** [comment]
i linked to a guide for using TS 5 with expo in the release notes btw
